FILE_EXTENSION_MAPPING = {
    "jpg": "images",
    "jpeg": "images",
    "png": "images",
    "gif": "images",
    "webp": "images",
    "svg": "images",
    "pdf": "documents",
    "doc": "documents",
    "docx": "documents",
    "xls": "documents",
    "xlsx": "documents",
    "mp4": "videos",
    "mov": "videos",
    "avi": "videos",
    "mp3": "audio",
    "wav": "audio",
    "zip": "archives",
    "rar": "archives",
    "7z": "archives",
}